[package]
name = "homepage"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17"
gloo-console = "0.2.3"
web-sys = { version = "0.3.60", features = ["Window", "Document", "Location"] }
